// MAGCF - Multi-Agent Generative Character Framework Copyright (c) 2026 Lipon / Psycho Games. All Rights Reserved.

#include "MAGCF/MAGCFComponents/MAGCFAIComponent.h"
#include "MAGCF/Characters/MAGCFCharacter.h"
#include "MAGCF/MAGCFComponents/MAGCFNeedComponent.h"
#include "MAGCF/MAGCFComponents/MAGCFActionSelectionComponent.h"
#include "MAGCF/AI/Profiles/MAGCFSettings.h"
#include "MAGCF/AI/Profiles/MAGCFPersonalityDataAsset.h"
#include "MAGCF/AI/LLM/MAGCFLLMService.h"
#include "MAGCF/AI/LLM/MAGCFLLMProviderBase.h"
#include "MAGCF/AI/LLM/MAGCFOpenAIProvider.h"
#include "MAGCF/AI/LLM/MAGCFGeminiProvider.h"
#include "MAGCF/AI/LLM/MAGCFAnthropicProvider.h"
#include "MAGCF/AI/LLM/MAGCFLocalProvider.h"
#include "Dom/JsonObject.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "MAGCF/MAGCF.h"

UMAGCFAIComponent::UMAGCFAIComponent()
{
    PrimaryComponentTick.bCanEverTick = true;

    SystemInstructions = TEXT("You are an execution arbiter for an NPC character brain. ")
        TEXT("Review the candidate actions generated by our utility system alongside recent action history. ")
            TEXT("Select EXACTLY ONE action from the candidate list that aligns best with personality guidelines. ")
                TEXT("Respond ONLY with structured JSON using this exact format: ")
                    TEXT("{\"Action\": \"E_GOAL_ENUM_NAME\", \"Reasoning\": \"Brief explanation.\"}");
}

void UMAGCFAIComponent::BeginPlay()
{
    Super::BeginPlay();

    const auto* const Settings = GetDefault<UMAGCFSettings>();
    if (!Settings) return;

    LLMService = NewObject<UMAGCFLLMService>(this);
    TSharedPtr<IMAGCFLLMProvider> ChosenProvider;

    switch (Settings->Provider)
    {
        case EMAGCFLLMProvider::EMP_OpenAI: ChosenProvider = MakeShared<FMAGCFOpenAIProvider>(); break;
        case EMAGCFLLMProvider::EMP_Gemini: ChosenProvider = MakeShared<FMAGCFGeminiProvider>(); break;
        case EMAGCFLLMProvider::EMP_Anthropic: ChosenProvider = MakeShared<FMAGCFAnthropicProvider>(); break;
        case EMAGCFLLMProvider::EMP_CustomLocal: ChosenProvider = MakeShared<FMAGCFLocalProvider>(); break;
        default: MAGCF_ERROR(TEXT("Selected LLM framework provider strategy is completely unhandled.")); break;
    }

    if (ChosenProvider.IsValid())
    {
        FString MappedKey = InstanceApiKeyOverride.IsEmpty() ? Settings->ApiKey : InstanceApiKeyOverride;
        FString TargetEndpoint = Settings->CustomEndpointOverride;

        if (Settings->Provider == EMAGCFLLMProvider::EMP_CustomLocal)
        {
            if (MappedKey.IsEmpty() || MappedKey == TEXT("local-ollama"))
            {
                MappedKey = TEXT("local-ollama");
            }
            if (TargetEndpoint.IsEmpty())
            {
                TargetEndpoint = TEXT("http://localhost:11434/v1/chat/completions");
            }
        }
        LLMService->Initialize(ChosenProvider, MappedKey, Settings->ModelName, TargetEndpoint);
        MAGCF_AI(TEXT("Global framework injection operational. Strategy dynamic bindings secure."));
    }
}

void UMAGCFAIComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

    if (bIsThinking || (GetWorld() && GetWorld()->GetTimeSeconds() < LLMRetryBlockUntil)) return;

    const auto* const OwnerChar = Cast<AMAGCFCharacter>(GetOwner());
    if (!OwnerChar || OwnerChar->IsBusy()) return;

    TimeSinceLastDecision += DeltaTime;
    if (TimeSinceLastDecision >= DecisionInterval)
    {
        TimeSinceLastDecision = 0.0f;
        RequestCandidateSelection();
    }
}

void UMAGCFAIComponent::RequestCandidateSelection()
{
    const auto* const OwnerChar = Cast<AMAGCFCharacter>(GetOwner());
    auto* const Selector = OwnerChar ? OwnerChar->GetActionSelectionComponent() : nullptr;
    if (!Selector) return;

    TArray<FMAGCFCandidateAction> SortedCandidates = Selector->GenerateCandidateActions(3);
    if (SortedCandidates.Num() == 0) return;

    bIsThinking = true;
    const FString FullPrompt = FString::Printf(TEXT("%s\n\nContext State Payload:\n%s"), *SystemInstructions, *FormatPayload(SortedCandidates));

    auto SuccessDelegate = FMAGCFLLMSuccess::CreateUObject(this, &UMAGCFAIComponent::OnLLMSuccess);
    auto FailureDelegate = FMAGCFLLMFailure::CreateUObject(this, &UMAGCFAIComponent::OnLLMFailure);

    if (LLMService)
    {
        LLMService->RequestCompletion(FullPrompt, SuccessDelegate, FailureDelegate);
    }
}

FString UMAGCFAIComponent::FormatPayload(const TArray<FMAGCFCandidateAction>& Candidates) const
{
    const auto* const OwnerChar = Cast<AMAGCFCharacter>(GetOwner());

    TArray<FString> CandidatesJson;
    for (const auto& Cand : Candidates)
    {
        const FString GoalStr = OwnerChar ? OwnerChar->GetGoalEnumToString(Cand.Goal) : TEXT("E_NONE");
        CandidatesJson.Add(FString::Printf(TEXT("{\"action\": \"%s\", \"utility_score\": %.2f}"), *GoalStr, Cand.FinalScore));
    }
    const FString JoinedCandidates = FString::Join(CandidatesJson, TEXT(", "));

    TArray<FString> HistoryStrings;
    if (OwnerChar)
    {
        for (const auto PastGoal : OwnerChar->GetRecentActionsArray())
        {
            HistoryStrings.Add(FString::Printf(TEXT("\"%s\""), *OwnerChar->GetGoalEnumToString(PastGoal)));
        }
    }
    const FString JoinedHistory = FString::Join(HistoryStrings, TEXT(", "));

    return FString::Printf(
        TEXT("{\n  \"recent_action_history\": [%s],\n  \"candidate_actions\": [%s]\n}"), *JoinedHistory, *JoinedCandidates);
}

FString UMAGCFAIComponent::CompileLLMContextPayload() const
{
    const auto* OwnerChar = Cast<AMAGCFCharacter>(GetOwner());
    if (!OwnerChar) return TEXT("{}");

    const auto* const NeedComponent = OwnerChar->GetNeedComponent();
    const auto* const PersonalityConfig = OwnerChar->GetPersonalityConfig();

    FString Archetype = TEXT("Unconfigured");
    float Social = 0.5f, Strength = 0.5f, Spend = 0.5f, PatienceVal = 0.5f, Calmness = 0.5f;
    FString Flavor = TEXT("Savory");
    float ThresholdPrice = 5.0f;
    FString FormattedTags = TEXT("");

    if (PersonalityConfig)
    {
        Archetype = PersonalityConfig->ArchetypeName;
        Social = PersonalityConfig->SocialTendency;
        Strength = PersonalityConfig->Fortitude;
        Spend = PersonalityConfig->SpendingTendency;
        PatienceVal = PersonalityConfig->Patience;
        Calmness = PersonalityConfig->Stability;
        Flavor = PersonalityConfig->PreferredFlavor;
        ThresholdPrice = PersonalityConfig->PriceThreshold;

        const FString Joined = FString::Join(PersonalityConfig->BehavioralFlavors, TEXT("\", \""));
        if (!Joined.IsEmpty())
        {
            FormattedTags = TEXT("\"") + Joined + TEXT("\"");
        }
    }

    const FString ExtractedNeedsMapData = NeedComponent ? NeedComponent->GetNeedsAsJSONString() : TEXT("\"Hunger\": 0.00");

    FString MoodString = TEXT("Neutral");
    switch (OwnerChar->GetCurrentMood())
    {
        case EMAGCFMood::E_HAPPY: MoodString = TEXT("Happy"); break;
        case EMAGCFMood::E_TIRED: MoodString = TEXT("Tired"); break;
        case EMAGCFMood::E_BORED: MoodString = TEXT("Bored"); break;
        default: break;
    }

    return FString::Printf(TEXT("{\n"
                                "  \"Identity\": {\n"
                                "    \"Archetype\": \"%s\",\n"
                                "    \"Tags\": [%s]\n"
                                "  },\n"
                                "  \"Psychology\": {\n"
                                "    \"IntroversionExtroversion\": %.2f,\n"
                                "    \"StrengthFortitude\": %.2f,\n"
                                "    \"FrugalityExtravagance\": %.2f,\n"
                                "    \"Patience\": %.2f,\n"
                                "    \"EmotionalStability\": %.2f\n"
                                "  },\n"
                                "  \"Taste\": {\n"
                                "    \"PreferredFlavor\": \"%s\",\n"
                                "    \"ComfortPriceLimit\": %.2f\n"
                                "  },\n"
                                "  \"NeedDirections\": {\n"
                                "    \"Hunger\": \"HIGHER=WORSE (0=full,100=starving)\",\n"
                                "    \"Fun\": \"HIGHER=WORSE (0=entertained,100=bored)\",\n"
                                "    \"Energy\": \"LOWER=WORSE (100=rested,0=exhausted)\"\n"
                                "  },\n"
                                "  \"LiveState\": {\n"
                                "    %s,\n"
                                "    \"WalletBalance\": %.2f,\n"
                                "    \"CurrentMoodProfile\": \"%s\"\n"
                                "  },\n"
                                "  \"DecisionRules\": {\n"
                                "    \"EatThreshold\": 50,\n"
                                "    \"RestThreshold\": 30,\n"
                                "    \"BoredThreshold\": 50,\n"
                                "    \"ImportantRule\": \"Never choose E_EAT if Hunger is 50 or below\"\n"
                                "  },\n"
                                "  \"AllowedActionSchema\": [\n"
                                "    { \"Action\": \"E_EAT\", \"ChooseWhen\": \"Hunger > 50\", \"AvoidWhen\": \"Hunger <= 50\" },\n"
                                "    { \"Action\": \"E_SIT_ON_GROUND\", \"ChooseWhen\": \"Energy < 30\" },\n"
                                "    { \"Action\": \"E_TALK_TO_PHONE\", \"ChooseWhen\": \"Fun > 50\" },\n"
                                "    { \"Action\": \"E_DANCE\", \"ChooseWhen\": \"Hunger < 30 AND Energy > 60 AND Fun < 30\" },\n"
                                "    { \"Action\": \"E_BOX\", \"ChooseWhen\": \"Energy >= 40\" },\n"
                                "    { \"Action\": \"E_PUSH_UP\", \"ChooseWhen\": \"Energy >= 50\" }\n"
                                "  ]\n"
                                "}"),
        *Archetype, *FormattedTags, Social, Strength, Spend, PatienceVal, Calmness, *Flavor, ThresholdPrice, *ExtractedNeedsMapData,
        OwnerChar->GetMoney(), *MoodString);
}

FString UMAGCFAIComponent::GatherCharacterContext() const
{
    return CompileLLMContextPayload();
}

void UMAGCFAIComponent::RequestNextAction()
{
    if (!LLMService) return;

    bIsThinking = true;
    const FString FullPrompt =
        FString::Printf(TEXT("%s\n\nInput Context Payload Data:\n%s"), *SystemInstructions, *GatherCharacterContext());

    auto SuccessDelegate = FMAGCFLLMSuccess::CreateUObject(this, &UMAGCFAIComponent::OnLLMSuccess);
    auto FailureDelegate = FMAGCFLLMFailure::CreateUObject(this, &UMAGCFAIComponent::OnLLMFailure);

    LLMService->RequestCompletion(FullPrompt, SuccessDelegate, FailureDelegate);
}

void UMAGCFAIComponent::OnLLMSuccess(const FString& CleanResponseText)
{
    ProcessStructuredOutput(CleanResponseText);
}

void UMAGCFAIComponent::ProcessStructuredOutput(const FString& JsonResponseString)
{
    bIsThinking = false;
    FString CleanedString = JsonResponseString.TrimStartAndEnd();

    const int32 FirstBrace = CleanedString.Find(TEXT("{"));
    const int32 LastBrace = CleanedString.Find(TEXT("}"), ESearchCase::CaseSensitive, ESearchDir::FromEnd);

    if (FirstBrace != INDEX_NONE && LastBrace != INDEX_NONE && LastBrace > FirstBrace)
    {
        CleanedString = CleanedString.Mid(FirstBrace, LastBrace - FirstBrace + 1);
    }
    else
    {
        MAGCF_ERROR(*FString::Printf(TEXT("LLM Output did not contain valid JSON wrapper boundaries:\n%s"), *CleanedString));
        OnLLMFailure(TEXT("JSON Structural Mapping Parse Validation Refusal."));
        return;
    }

    TSharedPtr<FJsonObject> ActionJson;
    const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(CleanedString);

    if (!FJsonSerializer::Deserialize(Reader, ActionJson) || !ActionJson.IsValid())
    {
        MAGCF_ERROR(*FString::Printf(TEXT("LLM JSON PARSE FAILED:\n%s"), *CleanedString));
        OnLLMFailure(TEXT("JSON Structural Mapping Parse Validation Refusal."));
        return;
    }

    FString ActionField;
    FString ReasoningField;

    if (!ActionJson->TryGetStringField(TEXT("Action"), ActionField) || ActionField.IsEmpty())
    {
        MAGCF_ERROR(TEXT("LLM response missing required functional field: Action"));
        OnLLMFailure(TEXT("Missing Action Field."));
        return;
    }

    if (!IsActionAllowed(ActionField))
    {
        MAGCF_ERROR(*FString::Printf(TEXT("LLM selected invalid action %s"), *ActionField));
        return;
    }

    LastAction = ActionField;
    if (GetWorld())
    {
        LastActionTimestamp = GetWorld()->GetTimeSeconds();
    }

    ActionJson->TryGetStringField(TEXT("Reasoning"), ReasoningField);
    OnLLMActionReceived.Broadcast(ActionField, ReasoningField);

    auto* const OwnerChar = Cast<AMAGCFCharacter>(GetOwner());
    if (OwnerChar)
    {
        const EMAGCFGoal ChosenGoal = OwnerChar->GetGoalStringToEnum(ActionField);
        OnActionSelected.Broadcast(ChosenGoal, ReasoningField);

        float CurrentHunger = 0.0f;
        if (const auto* const NeedComp = OwnerChar->GetNeedComponent())
        {
            const auto* const HungerState = NeedComp->GetNeed(TEXT("Hunger"));
            if (HungerState)
            {
                CurrentHunger = HungerState->CurrentValue;
            }
        }
        MAGCF_STORY(ActionField, ReasoningField, OwnerChar->GetMoney(), CurrentHunger);
    }
}

void UMAGCFAIComponent::OnLLMFailure(const FString& ErrorMessage)
{
    bIsThinking = false;
    if (GetWorld())
    {
        LLMRetryBlockUntil = GetWorld()->GetTimeSeconds() + 5.0f;
    }
    const auto* const OwnerChar = Cast<AMAGCFCharacter>(GetOwner());
    if (OwnerChar)
    {
        if (auto* const Selector = OwnerChar->GetActionSelectionComponent())
        {
            const auto BackupList = Selector->GenerateCandidateActions(1);
            if (BackupList.Num() > 0)
            {
                OnActionSelected.Broadcast(BackupList[0].Goal, TEXT("Deterministic System Fallback Active (LLM Failure Context)"));
            }
        }
    }
}